### ISSUE TITLE
Failed to log in.

### ISSUE THREAD

**Issue by AndreasEnemyr** [rastapasta/pokemon-go-mitm#209] opened 2016-08-21 07:58 UTC
I just got `Failed to log in.` when i try to login.. Should i use my local ip for the proxy?
192.168.1.xxx or what ip? 

I have installed the cert and setup the proxy

I think its the "proxy" part that fu*k'd me lol

what OS? **OSX El Capitan**
what distribution? **Apple**
does the proxy run on your home computer or a server? **Home computer**
if it's on your home computer are you using a router? **Yes**
if yes did you forward the port to your computer? **Yes, 8081 TCP/UDP to 192.168.1.xxx**
is your firewall on? **No**
if yes is the port 8081 open? **In the router yes**
are you on android? **No**
are you on ios? **Yes**

**Comment by jmoriau** [comment] 2016-08-21 10:34
You should use the external I (Google "ip address").

**Comment by jmoriau** [comment] 2016-08-21 10:35
Also on iOS you need to be jailbroken and have installed the correct packages (see README)

**Comment by gcsoftware** [comment] 2016-08-22 02:42
Having the same issue. Running an Ubuntu VPS with firewall disabled with confirmed 8081 port open.  I can see the "[<-] Request for GetPlayer  {}" being output, but receive "Failed to log in."

**Comment by trisk** [comment] 2016-08-24 07:06
Tried to check if any other iOS users are affected, but it looks like it's working fine for other people. @gcsoftware can you try a local setup to make sure your server isn't on a banned network?

**Comment by gcsoftware** [comment] 2016-08-28 00:16
@trisk That was the issue! Thanks.

**Comment by trisk** [comment] 2016-09-03 04:37
Closing since this is a configuration problem and the original poster has not responded.

**Closed by trisk** 2016-09-03 04:37 UTC
