### ISSUE TITLE
Behavior of example.renameAndCleanup.coffee - working as expected?

### ISSUE THREAD

**Issue by jdqx** [rastapasta/pokemon-go-mitm#58] opened 2016-07-28 02:13 UTC
The script example.renameAndCleanup.coffee broke my inventory. It released all of the pokemon and left the inventory at 3/250 pokemon, yet it is empty/blank. The 3 pokemon caught after this show up and change the size to 6/250 while only displaying the 3. Other scripts executed OK and didn't break anything. Debug was turned off by default, so I have no logs to show for that.

Commit: [ed22b8c](https://github.com/rastapasta/pokemon-go-mitm-node/commit/ed22b8cd422f2117353f735c520598f89b8783ad)

Log:
`Inventory processed (15 pokemon); waiting for login delay 15000ms
starting renamer (0 items)
finished renaming
starting releaser (15 items)
Requested release 17163346456179929494 : Weedle | cp15 | iv33
Requested release 12335144862660156595 : Pidgey | cp57 | iv33
Requested release 8079977386097116880 : Caterpie | cp10 | iv6
Requested release 13725528536275486842 : Gloom | cp22 | iv64
Requested release 6617271548074284104 : Rattata | cp10 | iv53
Requested release 1181213751368533234 : Pidgey | cp42 | iv46
Requested release 10627048133682971873 : Pidgey | cp60 | iv57
Requested release 14850804817170088282 : Doduo | cp11 | iv66
Requested release 12593823952883587527 : Rattata | cp35 | iv42
Requested release 17280305106487973858 : Rattata | cp22 | iv60
Requested release 14377216949099767034 : Venonat | cp94 | iv37
Requested release 15084113148366451293 : Weedle | cp24 | iv26
Requested release 523543273672424789 : Beedrill | cp54 | iv26
Requested release 9030297656159525660 : Weedle | cp15 | iv40
Requested release 2113598589383983957 : Bulbasaur | cp14 | iv66
finished releasing`

**Comment by rastapasta** [comment] 2016-07-28 03:02
urks.... that's a worst case. sorry to hear that has happened, ran the code after it got contributed and had no issues - but haven't checked for all  cases (like having it running from the beginning and/or starting it in the middle of the session). removed the example. sorry again for the inconvenience!

**Comment by trisk** [comment] 2016-07-28 16:47
It sounds like the issue is just a discrepancy between the inventory display in the app and the actual inventory; the released Pokémon CP and IVs match the script parameters. If it was some kind of missing or extra deltas it should just persist until the app is restarted.

**Comment by prajwalkman** [comment] 2016-07-28 19:21
I'm the author of the cleanup script. I don't quite understand what the issue is here. The script runs once only, doesn't keep watching your inventory - the first time it ran, it found 15 pokemon in your inventory, found that all 15 are under 800 CP and under 80% IV, and prompty released them, as it is supposed to. The ingame inventory doesn't immediately update - you have to wait until the next heartbeat (30 secs i think)

**Comment by prajwalkman** [comment] 2016-07-28 19:24
Oh, and the inventory count (3/250) includes eggs. That might be the reason you thought it was broken.

**Comment by prajwalkman** [comment] 2016-07-28 19:29
@rastapasta requesting reopen, since I'm pretty sure this was misdiagnosed.

**Comment by rastapasta** [comment] 2016-07-28 20:20
totally up for reopening and diagnostic, just had to remove it for now until its figured out - many people use this codebase with their real and not test accounts, loosing all what they 'worked for' is a uh-oh :)

**Comment by prajwalkman** [comment] 2016-07-28 20:40
@jdqx Can you confirm 3 things:

1. Your inventory said (18/250) before you ran the script
2. You had three eggs when you ran the script
3. You had 0 pokemon and 3 eggs after you ran the script

If these are true, then the script ran as intended. Your inventory isn't broken - there are no pokemon to show and the inventory count includes the number of eggs.

**Comment by prajwalkman** [comment] 2016-08-02 04:19
@rastapasta I've been using the script every night without issue for about a week now, so /shrug.

**Comment by jdqx** [comment] 2016-08-05 21:52
@prajwalkman @rastapasta Apologies, I did have 3 eggs. It's a misdiagnoses.

**Comment by rastapasta** [comment] 2016-08-08 15:12
@jdqx @prajwalkman thanks for the input! will put the script back in case we decide to reimplement craftRequest with the unknown6 handling. Closing until then but keeping it in mind! Cheers!

**Closed by rastapasta** 2016-08-08 15:12 UTC
Labels: question
